### PR TITLE
PHP >= 7.1 v4 Candidate

### LINKED ISSUE #157: Prismic::SearchForm url parameters are not correctly separated
https://github.com/prismicio/php-kit/blob/5670c79a639c09b96ad9460592713fad3a7f777d/src/Prismic/SearchForm.php#L265

Example options:
`['pageSize' => 2, 'page' => 2]` they are not separated correctly and the reason the response is incorrect.

With '**?**' as a separator the url looks like this:
`...?page=1&pageSize=100&...`

Once the question mark is changed to '**&**' the parameters are correctly separated:
`...&page=1&pageSize=100&...`

### PR DESCRIPTION
**Pull request by gsteel**
This is a very large PR from a fork I've been maintaining. There would need to be some cleanup, specifically the README and composer stuff. There's not a huge amount of BC breaks compared with v3 and it maintains compat with API v1 AFAICT. It's based on PR #150 and comes with a number of useful features.

Highlights:
* PSR-6/PSR-16 cache
* Hydrate documents to your own models to easily encapsulate logic
* Test coverage > 95%
* Predictable namespaced exceptions throughout

There's a bit more info here: https://github.com/netglue/prismic-php-kit/releases/tag/4.0.0

This should fix #157, #152 and #117 also maybe #155

### CODE REVIEW

**Comment by damyanovg** [comment]
Hello I am wondering if this PR is going to be merged soon?

**Comment by OwenMelbz** [comment]
@gsteel what ever happened with this?

**Comment by gsteel** [comment]
[This did…](https://github.com/netglue/prismic-php-kit)

**Comment by OwenMelbz** [comment]
Oh lovely :D feels like this product has been abandoned!

**Comment by gsteel** [comment]
The product is very much alive and well - I'm still using it all the time. There's just no love for PHPers. I maintain my own fork for my own specific needs - it's quite opinionated but contributions are welcome :)

**Comment by OwenMelbz** [comment]
Ah sorry, when i said "this product" I meant - this facet of the product, e.g. the PHP SDK.

It's a shame as looks great in so many ways until you try and use it with PHP then is less polished as everything else

**Comment by gsteel** [comment]
FWIW, I'm really happy using the fork. I do my best to follow semver and keep things stable. Kick the tyres or fork away ;) [Coverage is pretty good](https://codeclimate.com/github/netglue/prismic-php-kit)

**Pull request closed without merging**
